#!/usr/bin/env bash

if [ "$1" = "run" ]; then
  PORT=44444
  if [ -n "$2" ]; then
    PORT="$2"
  fi
  ./out/proxy "$PORT"
elif [ "$1" = "thread_count" ]; then
  watch "pgrep -u $USER proxy | xargs ps -o thcount"
elif [ "$1" = "mem" ]; then
  watch "pgrep -u $USER proxy | xargs ps -o rss"
else
  echo "usage: $0 run [port] | thread_count | mem"
fi
